export const TYPES = {
  SET_LOGGED_IN: 'SET_LOGGED_IN',
  SET_HEROES: 'SET_HEROES',
  SET_TOTAL_HEROES: 'SET_TOTAL_HEROES',
  SET_HERO: 'SET_HERO',
  CREATE_HERO: 'CREATE_HERO',
  SET_ACTS: 'SET_ACTS',
  SET_CART: 'SET_CART',
};
