export const TYPES = {
  SET_USER: 'SET_USER',
  SET_LOGGED_IN: 'SET_LOGGED_IN',
  SET_ERROR: 'SET_ERROR',
  SET_HEROES: 'SET_HEROES',
  SET_TOTAL_HEROES: 'SET_TOTAL_HEROES',
  SET_SEARCH_HEROES: 'SET_SEARCH_HEROES',
  SET_SEARCH_TOTAL: 'SET_SEARCH_TOTAL',
  SET_HERO: 'SET_HERO',
  CREATE_HERO: 'CREATE_HERO',
  SET_ACTS: 'SET_ACTS',
  SET_CART: 'SET_CART',
};
